spring:
  application:
    name: loans        # must match the file in your config repo (e.g., accounts.yml / accounts-prod.yml)
  config:
    import: "optional:configserver:http://configserver:8083"

server:
  servlet:
    context-path: /loan-service
  port: '8091'
